# [EDIT] - 2024-01-15 - Simplified Docker Compose for SQLite - Ediens Team
version: '3.8'

services:
  # No database services needed - using SQLite
  # Add any future services here (e.g., Redis for production caching)

networks:
  ediens_network:
    driver: bridge